In [5]:
import seafreeze.seafreeze as sf
import numpy as np
import matplotlib.pyplot as plt
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [7]:
n = 10
m = n+1
extent = [100,500,0,400]
# determine phase for three separate (P,T) conditions
P = np.linspace(extent[2],extent[3],m)
T = np.linspace(extent[0],extent[1],m)
data = np.zeros([m,m])

In [8]:
for i in range(0,m):
    for j in range(0,m):
        PT = np.array([P[i],T[j]])
        phase = sf.whichphase(PT)
        out = sf.seafreeze(PT, sf.phasenum2phase[int(phase)])
        data[i,j] = out.rho

Dimensions {'T'} contain values that fall outside the knot sequence for the given spline, which will result in extrapolation, which may not produce meaningful values.
Dimensions {'T'} contain values that fall outside the knot sequence for the given spline, which will result in extrapolation, which may not produce meaningful values.
Dimensions {'T'} contain values that fall outside the knot sequence for the given spline, which will result in extrapolation, which may not produce meaningful values.
Dimensions {'T'} contain values that fall outside the knot sequence for the given spline, which will result in extrapolation, which may not produce meaningful values.
Dimensions {'T'} contain values that fall outside the knot sequence for the given spline, which will result in extrapolation, which may not produce meaningful values.
Dimensions {'T'} contain values that fall outside the knot sequence for the given spline, which will result in extrapolation, which may not produce meaningful values

In [21]:
data2 = np.zeros([3,m*m])
for i in range(0,m):
    for j in range(0,m):
        data2[0,i*m+j]=P[i]
        data2[1,i*m+j]=T[j]
        data2[2,i*m+j]=data[i,j]

In [27]:
data2

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,   40.        ,
          40.        ,   40.        ,   40.        ,   40.        ,
          40.        ,   40.        ,   40.        ,   40.        ,
          40.        ,   40.        ,   80.        ,   80.        ,
          80.        ,   80.        ,   80.        ,   80.        ,
          80.        ,   80.        ,   80.        ,   80.        ,
          80.        ,  120.        ,  120.        ,  120.        ,
         120.        ,  120.        ,  120.        ,  120.        ,
         120.        ,  120.        ,  120.        ,  120.        ,
         160.        ,  160.        ,  160.        ,  160.        ,
         160.        ,  160.        ,  160.        ,  160.        ,
         160.        ,  160.        ,  160.        ,  200.        ,
         200.        ,  200.        ,  200.     

In [23]:
len(data2[0,:])

121

In [24]:
P

array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360., 400.])

In [25]:
T

array([100., 140., 180., 220., 260., 300., 340., 380., 420., 460., 500.])

In [26]:
data2

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,   40.        ,
          40.        ,   40.        ,   40.        ,   40.        ,
          40.        ,   40.        ,   40.        ,   40.        ,
          40.        ,   40.        ,   80.        ,   80.        ,
          80.        ,   80.        ,   80.        ,   80.        ,
          80.        ,   80.        ,   80.        ,   80.        ,
          80.        ,  120.        ,  120.        ,  120.        ,
         120.        ,  120.        ,  120.        ,  120.        ,
         120.        ,  120.        ,  120.        ,  120.        ,
         160.        ,  160.        ,  160.        ,  160.        ,
         160.        ,  160.        ,  160.        ,  160.        ,
         160.        ,  160.        ,  160.        ,  200.        ,
         200.        ,  200.        ,  200.     